---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: 애플리케이션 템플릿 및 태깅의 새로운 기능에 대해 알아보십시오. 
---
= 애플리케이션 템플릿 및 태깅의 새로운 기능
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
애플리케이션 템플릿 및 태깅의 새로운 기능에 대해 알아보십시오.



== 2022년 3월 3일



=== 이제 템플릿을 만들어 특정 작업 환경을 찾을 수 있습니다.

"기존 자원 찾기" 작업을 사용하면 작업 환경을 확인한 다음 볼륨 만들기와 같은 다른 템플릿 작업을 사용하여 기존 작업 환경에서 쉽게 작업을 수행할 수 있습니다. link:task-define-templates.html#examples-of-finding-existing-resources-and-enabling-services-using-templates["자세한 내용을 보려면 여기를 클릭하십시오"].



=== AWS에서 Cloud Volumes ONTAP HA 작업 환경을 구축할 수 있는 역량

AWS에서 Cloud Volumes ONTAP 작업 환경을 구축하기 위한 기존 지원이 확장되어 단일 노드 시스템 외에 고가용성 시스템을 구축할 수 있습니다. link:task-define-templates.html#create-a-template-for-a-cloud-volumes-ontap-working-environment["Cloud Volumes ONTAP 작업 환경에 대한 템플릿을 만드는 방법을 알아봅니다"].



== 2022년 2월 9일



=== 이제 템플릿을 구축하여 특정 기존 볼륨을 찾은 다음 Cloud Backup을 활성화할 수 있습니다.

새로운 "리소스 찾기" 작업을 사용하면 Cloud Backup을 설정할 모든 볼륨을 식별한 다음 클라우드 백업 작업을 사용하여 해당 볼륨에 대한 백업을 설정할 수 있습니다.

현재 Cloud Volumes ONTAP 및 온프레미스 ONTAP 시스템의 볼륨에 대한 지원이 제공됩니다. link:task-define-templates.html#find-existing-volumes-and-activate-cloud-backup["자세한 내용을 보려면 여기를 클릭하십시오"].



== 2021년 10월 31일



=== 이제 동기화 관계에 태그를 지정하여 쉽게 액세스할 수 있도록 관계를 그룹화하거나 분류할 수 있습니다.

link:concept-tagging.html["리소스 태깅에 대해 자세히 알아보십시오"].



== 2021년 10월 11일



=== 이제 기존 템플릿의 복제본을 만들 수 있습니다.

기존 템플릿과 매우 유사한 새 템플릿을 만들려는 경우 복제본을 만들면 많은 시간을 절약할 수 있습니다. 새 이름으로 복제한 다음 서식 파일을 고유하게 만드는 두 개의 항목을 변경하기만 하면 됩니다. link:task-define-templates.html#make-a-copy-of-a-template["서식 파일의 복사본을 만드는 방법을 알아봅니다"].



=== 이제 템플릿을 사용하여 생성한 볼륨에서 서비스를 사용하는 것이 훨씬 쉬워졌습니다.

작업을 수행하는 환경, 스토리지 VM 및 볼륨 이름을 식별하기 위해 변수를 선택해야 하기 전에 이제 템플릿에 이 정보가 추가됩니다. 따라서 Cloud Backup, Cloud Compliance 및 Replication 서비스를 새로 생성되는 볼륨에 간편하게 추가할 수 있습니다.



=== 특정 GCP 리소스에 대한 레이블을 지정할 수 있도록 지원이 추가되었습니다.

이제 Cloud Manager Tagging 서비스를 사용하여 GCP 리소스의 레이블을 관리할 수 있습니다. 리소스에 적용된 GCP 레이블 및 레이블 값을 볼 수 있으며, 이러한 레이블을 관리하는 다른 GCP 리소스에 적용할 수 있습니다. link:concept-tagging.html#resources-that-you-can-tag["라벨링할 수 있는 GCP 리소스를 참조하십시오"].



== 2021년 9월 2일



=== 이제 태깅 서비스를 사용하여 Azure 리소스의 태그를 관리할 수 있습니다.

리소스에 적용된 Azure 태그 및 태그 값을 볼 수 있으며, 관리 중인 다른 Azure 리소스에 해당 태그를 적용할 수 있습니다. link:concept-tagging.html#resources-that-you-can-tag["태그를 지정할 수 있는 Azure 리소스를 참조하십시오"].



=== 이제 몇 가지 추가 AWS EC2 리소스를 태깅할 수 있습니다.



== 2021년 8월 8일



=== 이제 템플릿을 사용하여 Cloud Volumes ONTAP 작업 환경을 만들 수 있습니다.

이 지원은 현재 AWS 환경에서만 제공되며 단일 노드 클러스터에만 제공됩니다. 자세한 내용은 를 참조하십시오 link:task-define-templates.html#create-a-template-for-a-cloud-volumes-ontap-working-environment["Cloud Volumes ONTAP 작업 환경에 대한 템플릿을 만듭니다"].



=== 새 기능을 사용하면 볼륨 템플릿의 볼륨에 태그를 추가할 수 있습니다.

태그를 사용하면 여러 리소스를 그룹화하여 자동화를 수행하거나 특정 부서 또는 지역에 비용을 할당할 수 있도록 애플리케이션, 지역 또는 부서를 식별할 수 있습니다.



=== 이제 Cloud Manager에서 AWS EC2 인스턴스의 태그를 관리할 수 있습니다.

EC2 인스턴스에 적용된 AWS 태그 및 태그 값을 보고, 관리하는 다른 EC2 인스턴스에 해당 태그를 적용할 수 있습니다. link:concept-tagging.html["태그 지정에 대해 자세히 알아보세요"].



== 2021년 7월 13일



=== 템플릿을 정의할 때 복제 서비스를 사용할 수 있도록 지원이 추가되었습니다.

이제 원하는 서식 파일을 추가할 수 있습니다 link:task-define-templates.html#add-replication-functionality-to-a-volume["생성 중인 볼륨의 데이터를 복제합니다"] 를 사용하여 다른 볼륨으로 이동합니다 https://docs.netapp.com/us-en/cloud-manager-replication/concept-replication.html["복제 서비스"].

데이터를 다른 NetApp 스토리지 시스템으로 복제하고 2차 데이터를 지속적으로 업데이트함으로써 데이터가 최신 상태로 유지되고 필요할 때마다 사용할 수 있고



=== 템플릿 설정에서 "표류된" 모든 볼륨이 포함된 보고서를 다운로드합니다.

이러한 방식으로 이러한 볼륨을 식별하고 볼륨을 규정 준수 상태로 되돌릴 사람을 할당할 수 있습니다. 을 참조하십시오 link:task-check-template-compliance.html#create-a-drift-report-for-non-compliant-resources["변경 사항 보고서를 다운로드하는 방법"].



=== 새 태그 지정 서비스가 해제되었습니다.

새로운 Cloud Manager 기능을 사용하면 기존 ONTAP 리소스에 태그를 적용하여 리소스를 구성 및 관리할 수 있습니다. 태그는 리소스를 그룹화하여 애플리케이션, 환경, 지역, 청구 코드, 클라우드 공급자 등을 식별하는 데 사용할 수 있는 메타데이터입니다. 있습니다.

link:concept-tagging.html["태그 지정에 대해 자세히 알아보세요"].



== 2021년 6월 7일



=== 이제 사용자가 템플릿을 실행할 때 특정 작업을 조건부로 활성화할 수 있습니다.

예를 들어, Cloud Volumes ONTAP 스토리지 효율성을 활성화한 상태에서 NetApp 볼륨을 생성한 경우 Cloud Backup도 해당 볼륨에 활성화됩니다. 스토리지 효율성이 설정되지 않으면 Cloud Backup이 활성화되지 않습니다.



=== 이제 템플릿을 사용하여 온프레미스 ONTAP 시스템에서 볼륨을 생성할 수 있습니다.



=== 템플릿을 만들 때 "드리프트"라는 새로운 기능이 옵션으로 추가되었습니다.

Cloud Manager는 이 기능을 사용하여 템플릿의 매개 변수에 대해 입력한 하드 코딩된 값을 모니터링할 수 있습니다. 스토리지 관리자가 해당 템플릿을 사용하여 볼륨을 생성한 후 나중에 Cloud Manager가 템플릿 정의에 더 이상 맞춰지지 않도록 매개 변수 값이 변경되었다고 볼 경우, 설계된 템플릿에서 "표류된" 모든 볼륨을 볼 수 있습니다. 이러한 방식으로 이러한 볼륨을 식별하고 변경하여 규정을 준수할 수 있습니다.



== 2021년 5월 2일



=== 이제 볼륨 템플릿을 생성할 때 Cloud Data Sense를 통합할 수 있습니다.

이제 새로 생성된 각 볼륨에 대해 Data Sense를 활성화하거나 새로 생성된 각 볼륨에 대해 Cloud Backup을 활성화하거나 생성된 볼륨에서 백업과 규정 준수를 모두 사용할 수 있는 템플릿을 생성할 수 있습니다.
